[tool.poetry]
name = "terra-sdk-python"
version = "1.0.0"
description = "The Python SDK for Terra"
authors = ["Terraform Labs, PTE. <engineering@terra.money>"]
license = "MIT"
readme = "README.md"
homepage = "https://docs.terra.money/sdk"
repository = "https://github.com/terra-project/terra-sdk-python"
documentation = "https://docs.terra.money/sdk"
keywords = ["jigu", "blockchain", "terra", "defi", "crypto"]
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]
packages = [
    { include = "terra_sdk" }
]

[tool.poetry.dependencies]
python = "^3.6"
bip32utils = "^0.3.post4"
ecdsa = "^0.16.1"
mnemonic = "^0.19"
bech32 = "^1.2.0"
aiohttp = "^3.7.3"
attrs = "^20.3.0"

[tool.poetry.dev-dependencies]
pip = "^21.0"
wheel = "^0.36.2"
watchdog = "^1.0.2"
flake8 = "^3.8.4"
tox = "^3.21.2"
coverage = "^5.3.1"
pytest = "^6.2.1"
mypy = "^0.800"
pytest-runner = "^5.2"
pytest-sugar = "^0.9.4"
pytest-mock = "^3.5.1"
black = "^20.8b1"
isort = "^5.7.0"
pytest-cov = "^2.11.1"


[tool.tox]
legacy_tox_ini = """
[tox]
envlist = py36, py37, py38, py39, flake8

[travis]
python =
    3.6: py36
    3.7: py37
    3.8: py38
    3.9: py39

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 terra_sdk

[flake8]
# Recommend matching the black line length (default 88),
# rather than using the flake8 default of 79:
max-line-length = 88
extend-ignore =
    # See https://github.com/PyCQA/pycodestyle/issues/373
    E203,

[testenv]
setenv =
    PYTHONPATH = {toxinidir}
deps =
    -r{toxinidir}/requirements_dev.txt
; If you want to make tox run the tests with the same versions, create a
; requirements.txt with the pinned versions and uncomment the following line:
;     -r{toxinidir}/requirements.txt
commands =
    pip install -U pip
    pytest --basetemp={envtmpdir}

[pytest]
addopts = -rsxX -l --tb=short --strict
"""

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
